apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: adam
spec:
  request: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VZV1JoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQUxSY0k2OWEvYzhGeVgwWi9tcnQxNU1KRzJlVnFYdm5qYzBKZFMydDY0em5KUFA0Cm5YL09aNlZNKzNUYkgrWEVZc2dpSW9ZS0FjcEIrTUdsRXlpR2Y2UHhxeHNNMDhlNURCTHlaUEo0RVdVUExDVUIKeE9IeTRsUTdIRnBSL2s2U09yenlya2F3bU94Z0xIbDJHLzlHbHoyajJOd1JpZUdXTWF2eW5SdGw0T1NHMk5nNQpVUldyTE40ZVVDSTRnRUZLcUh3L2Jkc3ZiUVNGUFFURWpBZmpIbHBydHRESHpkMW80Tmd6WFg0bXdSM2VRQVpvCkhEcGx5L2NWQmF0NVF3ZHhHa3hXcHVneDcvQzVxWUFuQjBsK0h4cXZYVWc4UkQwaElSbkpSUk82SXhKT2RRZ1EKNlgrejNXblplRnZjR1BBdmQ2RnluazZwWnhoc3RKTHRWb3RoWmMwQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQkhOMnY3MkR3YmpqTlB2UDB6UkxvUXU4U3FtSFNBdHdwTlp5MlU3QklKdEFMTXNSTFJSeVdGClkydWhaUXl5VmZXalRVSTZWUGhnNGZIRjJ3WmZ2c21VWnMzSDQ3WUVJblp1RTJzMnppWEYycEgrbndKZ1VDaUsKa01qd3o3MnpPRS9DRlkxQllFKzNBRHExd1pDZHg0eHkwcGErNzlWOGRPVGlPeHFqS1JkemlNeCtsSkUzb2p1UgpFWEJBZTU4Tm5teWxFRTR3QXdQaTlwNDdIYnJ5YmZReXRPZGpwbXdOdnZOZUZCaWFPRm5NdUR1ekhZd2FJQkYvClhsd1VhS1A5a0xjeXZuN09UR3dUb1kwbnkvZmFISFhoZC9CNHNFTkN6MSs2dHlNQThvQ0p3OWdXYWFhT084WUwKY2NOVklVQmMzaXlhUFpKNGV0TjY4ejF6ZXVrdTRiejgKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg=="
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000  # Optional: 1 year
  usages:
  - client auth

