apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rolling-update
spec:
  replicas: 5
  strategy:
    canary:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      app: rolling-update
  template:
    metadata:
      labels:
        app: rolling-update
    spec:
      containers:
      - name: rolling-update
        image: gauravhalnawar2705/blue-green-deployment:latest
        imagePullPolicy: Always
        env:
        - name: html_name
          value: "app-v1.html"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: rolling-update
spec:
  type: NodePort
  selector:
    app: rolling-update
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007
