apiVersion: v1
kind: Secret
metadata:
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-sa  # this is important we need sa created 
type: kubernetes.io/service-account-token







