apiVersion: v1
kind: Pod
metadata: 
  name: memory-demo2
  namespace: mem-exmple
spec:
  containers:
  - name: memory-demo2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
