apiVersion: v1
kind: Pod
metadata: 
  name: memory-demo3
  namespace: mem-exmple
spec:
  containers:
  - name: memory-demo3-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "1000Gi"
      limits:
        memory: "1000Gi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
