# cd /home/ubuntu/kind-cluster/kubernetes/nginx/django-notes-app/k8s
# ls
# vi liveness_probe.yml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: juhisinha/notes-app-k8s
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        

# vi namespace.yml

kind: Namespace
apiVersion: v1
metadata:
  name: nginx

# vi service.yml

kind: Service
apiVersion: v1
metadata:
  name: notes-app-service
  namespace: nginx
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP


# kubectl apply -f namespace.yml
# kubectl apply -f service.yml
# kubectl apply -f liveness_probe.yml
# kubectl get pods -n nginx
# kubectl describe pod/notes-app-deployment-7ddc5bc698-29jc7 -n nginx
# kubectl get svc -n nginx
# sudo -E  kubectl port-forward service/notes-app-service -n nginx 8080:8000 --address=0.0.0.0

OR
# sudo -E  kubectl port-forward service/notes-app-service -n nginx 81:8000 --address=0.0.0.0

# # access app: Public-IP:8000/ or 
# # access app: Public-IP:81/







          
