apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
  labels:
    name: init-pod
spec: 
  containers:
    - name: my-appcontainer
      image: busybox:1.28
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: custom-cm
              key: firstname
        - name: LASTNAME
          valueFrom:
            configMapKeyRef:
              name: custom-cm
              key: lastname
      command: ['sh', '-c', 'echo "App running with $FIRSTNAME $LASTNAME" && sleep 3600']
