apiVersion: v1
kind: Pod
metadata: 
  name: init-pod
  labels:
    name: init-pod
spec: 
  containers:
    - name: my-appcontainer
      image: busybox:1.28
      envFrom:
        - configMapRef:
            name: custom-cm
      command: ['sh', '-c', 'echo "App running with $firstname $lastname" && sleep 3600']
