# vi jobs.yml

kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh", "-c" ,"echo Hello Dosto! && sleep 10"]
      restartPolicy: Never


# kubectl apply -f jobs.yaml
# kubectl get job -n nginx
# kubectl get pods -n nginx
# kubectl logs -f pod/demo-job-6nt77 -n nginx

# If we want to run the job again then we need to delete and apply again.
# kubectl delete -f jobs.yml
# kubectl apply -f jobs.yml
# kubectl get pods -n nginx
# kubectl get job -n nginx
# kubectl logs -f pod/demo-job-4dhhb -n nginx

