# echo "root" | base64
# vi secrets.yml

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo=  # base64 encoded for "root"


# vi statefulsets.yml

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql

spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: MYSQL_DATABASE

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


# kubectl apply -f secrets.yml
# kubectl get secret -n mysql
# ubuntu@ip-172-31-37-222:~/kind-cluster/kubernetes/mysql$ kubectl get secret -n mysql
NAME           TYPE     DATA   AGE
mysql-secret   Opaque   1      33s
# opaque means: Its value is encoded we can’t see it directly.

# kubectl apply -f statefulsets.yml
# kubectl get pods -n mysql
# kubectl exec -it mysql-statefulset-1 -n mysql – bash
# mysql -u root -p
# Enter password: root
#  show databases;
# exit
# exit

