# cd /home/ubuntu/kind-cluster/kubernetes/nginx
# kubectl delete -f namespace.yml
# cd ..
# mkdir mysql
# cd mysql
# vi namespace.yml (code in repo)
# kubectl apply -f namespace.yml

# vi statefulset.yml

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql-statefulset
  namespace: mysql

spec:
  serviceName: mysql-service
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306

        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

        - name: MYSQL_DATABASE
          value: devops

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

# kubectl apply -f statefulset.yml

# vi service.yml (code in repo)
# kubectl apply -f service.yml

# kubectl get pods -n mysql
# watch kubectl get pods -n mysql
# kubectl get svc -n mysql
# kubectl get pods -n mysql
# kubectl exec -it mysql-statefulset-0 -n mysql -- bash
# mysql -u root -p
# Enter password: root
# exit 
# exit

# # kubectl delete pod mysql-statefulset-0 -n mysql
# kubectl get pods -n mysql
# we can see here that the pod which deleted, the pod is created again with same name.
