apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-dev
  namespace: argocd
spec:
  project: dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/devops4solutions/deploy-argocd-app.git
      targetRevision: main
      ref: values
    - repoURL: https://devops4solutions.github.io/springboot-helm-chart/
      chart: springboot
      targetRevision: 0.1.5
      helm:
        valueFiles:
          - $values/deploy/dev/values.yaml
